package storage

import (
	"context"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"
)

// PublicPath is the URL path prefix local files are served under.
const PublicPath = "/uploads/"

// Local stores files in a directory on disk and serves them over HTTP.
type Local struct {
	dir     string
	baseURL string // e.g. "http://localhost:8080"
}

// NewLocal creates the directory if needed and returns a Local storage.
func NewLocal(dir, publicBaseURL string) (*Local, error) {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, fmt.Errorf("storage: create upload directory: %w", err)
	}
	return &Local{dir: dir, baseURL: strings.TrimRight(publicBaseURL, "/")}, nil
}

// Save writes the file and returns its public URL.
func (l *Local) Save(_ context.Context, name, _ string, content io.Reader) (string, error) {
	// Names are generated by the server, but never trust a path anyway.
	if name != filepath.Base(name) || strings.HasPrefix(name, ".") {
		return "", errors.New("storage: invalid file name")
	}
	path := filepath.Join(l.dir, name)

	// O_EXCL: fail instead of overwriting an existing file.
	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o644)
	if err != nil {
		return "", fmt.Errorf("storage: create file: %w", err)
	}
	if _, err := io.Copy(f, content); err != nil {
		f.Close()
		os.Remove(path)
		return "", fmt.Errorf("storage: write file: %w", err)
	}
	if err := f.Close(); err != nil {
		os.Remove(path)
		return "", fmt.Errorf("storage: close file: %w", err)
	}
	return l.baseURL + PublicPath + name, nil
}

// Handler serves stored files under PublicPath. Directory listings are
// disabled, and since file names are random and never reused, browsers may
// cache files for a long time.
func (l *Local) Handler() http.Handler {
	files := http.StripPrefix(PublicPath, http.FileServer(http.Dir(l.dir)))
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if strings.HasSuffix(r.URL.Path, "/") {
			http.NotFound(w, r)
			return
		}
		w.Header().Set("X-Content-Type-Options", "nosniff")
		w.Header().Set("Cache-Control", "public, max-age=31536000, immutable")
		files.ServeHTTP(w, r)
	})
}
